
import React from 'react';
import { Icons } from './components/icons';
import { Translations } from './types';

export const translations: { [key: string]: Translations } = {
    es: {
        // General & Config
        mainTitle: "Asistente de Alta de Autónomos",
        mainSubtitle: "Complete todos los pasos para registrar al nuevo cliente.",
        navHint: "Navegue entre pasos haciendo clic en los iconos.",
        anterior: "Anterior",
        siguiente: "Siguiente",
        volver: "Volver",
        finalizar: "Finalizar y Guardar",
        registrarOtro: "Registrar Otro Cliente",
        si: "Sí",
        no: "No",
        generarConIA: "Generar con IA",
        generando: "Generando...",
        errorIA: "Error de IA",
        noEspecificado: "No especificado",
        // Pasos
        step1Title: "Datos Personales",
        step2Title: "Residencia Fiscal",
        step3Title: "Actividad",
        step4Title: "Otros Datos",
        step5Title: "Resumen y Edición",
        // Paso 1
        dniNie: "DNI / NIE",
        nacionalidad: "Nacionalidad",
        nombre: "Nombre",
        apellido1: "Primer Apellido",
        apellido2: "Segundo Apellido",
        fechaNacimiento: "Fecha de Nacimiento",
        direccion: "Dirección",
        tipoVia: "Tipo Vía",
        nombreVia: "Nombre Vía",
        numero: "Nº",
        piso: "Piso",
        puerta: "Puerta",
        codigoPostal: "Cód. Postal",
        poblacion: "Población",
        provincia: "Provincia",
        nombrePadre: "Nombre del Padre (sin apellidos)",
        nombreMadre: "Nombre de la Madre (sin apellidos)",
        telefono: "Teléfono de Contacto",
        email: "Email de Contacto",
        contactoOficialHint: "Para notificaciones oficiales",
        // Paso 2
        fechaLlegada: "Fecha demostrable de llegada a España",
        comentariosLlegada: "Comentarios sobre la llegada",
        resideMas183Dias: "¿Ha residido más de 183 días en España durante el último año natural?",
        datoAdicional: "Dato Adicional Requerido",
        paisResidenciaFiscalHint: "Indique dónde pagaba sus impuestos antes de llegar a España.",
        paisResidenciaFiscal: "País de residencia fiscal anterior",
        // Paso 3
        iban: "IBAN de la cuenta bancaria",
        cuentaAbiertaCon: "Cuenta abierta con",
        pasaporte: "Pasaporte",
        alertaPasaporteTitle: "Información: Cuentas con Pasaporte",
        alertaPasaporteContent: "La Seguridad Social acepta la domiciliación si el titular de la cuenta coincide con el titular del alta. Sin embargo, Hacienda opera exclusivamente con NIF (DNI/NIE). Una cuenta con pasaporte no será válida para cargos/devoluciones de impuestos.\n\n**Acción recomendada:** Solicite al banco el cambio a una cuenta asociada a su NIE lo antes posible.",
        actividadDefinida: "¿Tiene la actividad económica decidida?",
        descripcionActividad: "Descripción de la actividad económica",
        descripcionActividadHint: "Sea breve o use palabras clave para la IA",
        actividadGenericaInfo: "Se imputará una actividad genérica (Intermediario de comercio) que se modificará más adelante.",
        situacionLaboral: "¿Está trabajando por cuenta ajena (nómina)?",
        // Paso 4
        ejerceEnLocal: "¿Va a ejercer la actividad en un local?",
        infoLocal: "Deberá aportar el contrato de arrendamiento o escritura de propiedad para el alta de la actividad en esa dirección.",
        mutua: "Mutua de autónomos (preferencia)",
        rendimientoNetoPrevisto: "Rendimiento neto mensual previsto (€)",
        infoRendimientoPrevisto: "Este dato es clave para determinar su base de cotización. Si disfruta de tarifa reducida, afectará a partir del segundo año. Si no, determinará la base provisional desde el inicio.",
        disfrutaTarifaReducida: "¿Cumple requisitos para la tarifa reducida?",
        baseCotizacionElegida: "Base de cotización elegida (€)",
        baseCotizacionHint: "Consulte la página de enlaces para info.",
        infoIngresosReales: "Al no optar por tarifa reducida, se aplica el sistema de cotización por ingresos reales. Deberá elegir una base de cotización provisional.",
        operaIntracomunitario: "¿Prevé operaciones intracomunitarias (clientes/proveedores UE)?",
        infoROI: "Para operar intracomunitariamente, se debe solicitar el alta en el ROI. No se puede facturar sin IVA a clientes UE hasta tener el alta confirmada. Antes de facturar, compruebe que su cliente esté en el censo VIES.",
        incluirBeneficiarios: "¿Desea incluir beneficiarios en la Tarjeta Sanitaria?",
        infoTarifaReducidaTitle: "Info: Tarifa Reducida y Cotización",
        infoTarifaReducidaContent: "Primer año: cuota reducida de ~80€/mes, prorrogable 12 meses más si sus ingresos no superan el SMI. Requisito: no haber estado de alta en los 2 años anteriores (o 3 si ya disfrutó de esta cuota).",
        infoBeneficiariosTitle: "Info: Incluir Beneficiarios",
        infoBeneficiariosContent: "Para incluir beneficiarios (cónyuge, hijos), debe solicitarse en los 4 días siguientes al alta. Requisito: los beneficiarios deben tener DNI, TIE o CUE. Este trámite tiene un coste adicional.",
        // Paso 5
        resumenTitle: "Revisar y Editar",
        resumenSubtitle: "Revise todos los datos. Puede hacer clic en cualquier campo para editarlo al instante.",
        comentariosFinales: "Comentarios Adicionales del Cliente",
        comentariosFinalesPlaceholder: "Añada cualquier aclaración aquí...",
        descargarPdf: "PDF",
        descargarExcel: "Excel",
        descargarTxt: "Texto",
        descargarJson: "JSON",
        descargarParaBenet: "ZIP para Asesoría",
        // Paso 6
        procesoFinalizado: "¡Proceso Finalizado!",
        procesoFinalizadoSubtitle: "Se han generado y guardado los documentos con el resumen de los datos.",
        pdfEditableHint: "Recuerde que el PDF es editable.",
        recordatorios: "Recordatorios Importantes",
        recordatorioCertificado: "No olvide solicitar al cliente el Certificado Digital (.p12 o .pfx) y su contraseña.",
        recordatorioLocal: "Si ejercerá en un local, se necesita copia del contrato de alquiler o traspaso.",
        recordatorioBeneficiarios: "Si se incluyeron beneficiarios, el trámite debe realizarse en los 4 días siguientes al alta.",
        // Guardar/Cargar
        guardarProgreso: "Guardar Progreso",
        cargarProgreso: "Cargar Progreso",
        // Header Buttons
        cambiarIdioma: "Cambiar idioma",
        activarModoClaro: "Activar modo claro",
        activarModoOscuro: "Activar modo oscuro",
        pantallaCompleta: "Pantalla completa",
        // Alertas y Errores
        pantallaCompletaError: "Error al intentar el modo de pantalla completa",
        datosCargados: "Datos cargados correctamente.",
        errorCargar: "Error al leer el archivo. Asegúrate de que es un archivo de guardado válido.",
        errorDesconocido: "Ocurrió un error desconocido.",
        errorAiCliente: "El cliente de IA no está inicializado. Compruebe la configuración de la API Key.",
        errorAiRespuestaVacia: "La respuesta de la IA estaba vacía.",
        errorAiGenerar: "No se pudo generar la descripción. Por favor, inténtelo de nuevo más tarde o escríbala manually.",
        // Exportación
        campo: "Campo",
        valor: "Valor",
        seccion: "Sección",
        resumenCliente: "Resumen Cliente",
        resumenAlta: "Resumen_Alta",
        paraBenet: "PARA_BENET_ASESORIA",
        cliente: "Cliente",
        // Accesibilidad
        ariaLabelEditable: {
            part1: 'Valor para',
            part2: 'es',
            part3: 'Clic para editar.',
        },
    },
    en: {
        // General & Config
        mainTitle: "Freelancer Onboarding Assistant",
        mainSubtitle: "Complete all steps to register the new client.",
        navHint: "Navigate between steps by clicking the icons.",
        anterior: "Previous",
        siguiente: "Next",
        volver: "Back",
        finalizar: "Finalize and Save",
        registrarOtro: "Register Another Client",
        si: "Yes",
        no: "No",
        generarConIA: "Generate with AI",
        generando: "Generating...",
        errorIA: "AI Error",
        noEspecificado: "Not specified",
        // Steps
        step1Title: "Personal Details",
        step2Title: "Tax Residence",
        step3Title: "Activity",
        step4Title: "Other Details",
        step5Title: "Summary & Edit",
        // Step 1
        dniNie: "DNI / NIE (ID Number)",
        nacionalidad: "Nationality",
        nombre: "First Name",
        apellido1: "First Surname",
        apellido2: "Second Surname",
        fechaNacimiento: "Date of Birth",
        direccion: "Address",
        tipoVia: "Street Type",
        nombreVia: "Street Name",
        numero: "No.",
        piso: "Floor",
        puerta: "Door",
        codigoPostal: "Postal Code",
        poblacion: "City / Town",
        provincia: "Province",
        nombrePadre: "Father's Name (no surnames)",
        nombreMadre: "Mother's Name (no surnames)",
        telefono: "Contact Phone",
        email: "Contact Email",
        contactoOficialHint: "For official notifications",
        // Step 2
        fechaLlegada: "Verifiable date of arrival in Spain",
        comentariosLlegada: "Comments about arrival",
        resideMas183Dias: "Have you resided in Spain for more than 183 days in the last calendar year?",
        datoAdicional: "Additional Data Required",
        paisResidenciaFiscalHint: "Indicate where you paid your taxes before arriving in Spain.",
        paisResidenciaFiscal: "Previous country of tax residence",
        // Step 3
        iban: "IBAN of the bank account",
        cuentaAbiertaCon: "Account opened with",
        pasaporte: "Passport",
        alertaPasaporteTitle: "Information: Accounts with Passport",
        alertaPasaporteContent: "Social Security accepts direct debit if the account holder matches the registration holder. However, the Tax Agency (Hacienda) operates exclusively with NIF (DNI/NIE). An account opened with a passport will not be valid for tax charges/refunds.\n\n**Recommended action:** Request the bank to change to an account associated with your NIE as soon as possible.",
        actividadDefinida: "Is the economic activity decided?",
        descripcionActividad: "Description of the economic activity",
        descripcionActividadHint: "Be brief or use keywords for the AI",
        actividadGenericaInfo: "A generic activity (Commercial Intermediary) will be assigned, to be modified later.",
        situacionLaboral: "Are you currently employed (on a payroll)?",
        // Step 4
        ejerceEnLocal: "Will you carry out the activity in a physical location?",
        infoLocal: "You must provide the lease contract or property deed to register the activity at that address.",
        mutua: "Freelancer's mutual insurance (preference)",
        rendimientoNetoPrevisto: "Estimated net monthly income (€)",
        infoRendimientoPrevisto: "This data is key to determining your contribution base. If you benefit from the reduced rate, it will affect you from the second year. If not, it will determine the provisional base from the beginning.",
        disfrutaTarifaReducida: "Do you meet the requirements for the reduced rate?",
        baseCotizacionElegida: "Chosen contribution base (€)",
        baseCotizacionHint: "Check the links page for info.",
        infoIngresosReales: "By not opting for the reduced rate, the system of contribution based on real income applies. You must choose a provisional contribution base.",
        operaIntracomunitario: "Do you anticipate intra-community operations (EU clients/suppliers)?",
        infoROI: "To operate intra-community, you must apply for registration in the ROI. You cannot invoice EU clients without VAT until the registration is confirmed. Before invoicing, check that your client is in the VIES census.",
        incluirBeneficiarios: "Do you want to include beneficiaries in the Health Card?",
        infoTarifaReducidaTitle: "Info: Reduced Rate and Contribution",
        infoTarifaReducidaContent: "First year: reduced fee of ~€80/month, extendable for another 12 months if your income does not exceed the National Minimum Wage. Requirement: not having been registered in the last 2 years (or 3 if you have already enjoyed this fee).",
        infoBeneficiariosTitle: "Info: Including Beneficiaries",
        infoBeneficiariosContent: "To include beneficiaries (spouse, children), it must be requested within 4 days of registration. Requirement: beneficiaries must have a DNI, TIE, or CUE. This procedure has an additional cost.",
        // Step 5
        resumenTitle: "Review and Edit",
        resumenSubtitle: "Review all the data. You can click on any field to edit it instantly.",
        comentariosFinales: "Additional Client Comments",
        comentariosFinalesPlaceholder: "Add any clarifications here...",
        descargarPdf: "PDF",
        descargarExcel: "Excel",
        descargarTxt: "Text",
        descargarJson: "JSON",
        descargarParaBenet: "ZIP for Agency",
        // Step 6
        procesoFinalizado: "Process Finished!",
        procesoFinalizadoSubtitle: "The summary documents have been generated and saved.",
        pdfEditableHint: "Remember the PDF is editable.",
        recordatorios: "Important Reminders",
        recordatorioCertificado: "Don't forget to request the Digital Certificate (.p12 or .pfx) and its password from the client.",
        recordatorioLocal: "If operating from a location, a copy of the rental or transfer contract is needed.",
        recordatorioBeneficiarios: "If beneficiaries were included, the process must be completed within 4 days of registration.",
        // Guardar/Cargar
        guardarProgreso: "Save Progress",
        cargarProgreso: "Load Progress",
        // Header Buttons
        cambiarIdioma: "Change language",
        activarModoClaro: "Enable light mode",
        activarModoOscuro: "Enable dark mode",
        pantallaCompleta: "Fullscreen",
        // Alertas y Errores
        pantallaCompletaError: "Error attempting to enable full-screen mode",
        datosCargados: "Data loaded successfully.",
        errorCargar: "Error reading file. Make sure it is a valid save file.",
        errorDesconocido: "An unknown error occurred.",
        errorAiCliente: "AI client is not initialized. Check your API Key configuration.",
        errorAiRespuestaVacia: "The AI response was empty.",
        errorAiGenerar: "Could not generate description. Please try again later or write it manually.",
        // Exportación
        campo: "Field",
        valor: "Value",
        seccion: "Section",
        resumenCliente: "Client Summary",
        resumenAlta: "Onboarding_Summary",
        paraBenet: "FOR_BENET_AGENCY",
        cliente: "Client",
        // Accesibilidad
        ariaLabelEditable: {
            part1: 'Value for',
            part2: 'is',
            part3: 'Click to edit.',
        },
    },
};

export const stepsConfig = (t: Translations) => [
    { number: 1, title: t.step1Title, icon: React.createElement(Icons.User) },
    { number: 2, title: t.step2Title, icon: React.createElement(Icons.MapPin) },
    { number: 3, title: t.step3Title, icon: React.createElement(Icons.Briefcase) },
    { number: 4, title: t.step4Title, icon: React.createElement(Icons.FileText) },
    { number: 5, title: t.step5Title, icon: React.createElement(Icons.Check) },
];
